export { default as AirIcon } from "./air.svg";
export { default as ArrowLeft } from "./arrow-left.svg";
export { default as AstralHand } from "./astral-hand.svg";
export { default as EarthIcon } from "./earth.svg";
export { default as FireIcon } from "./fire.svg";
export { default as HeadAndHeart } from "./head-and-heart.svg";
export { default as Logo } from "./logo.svg";
export { default as ScanningHand } from "./scanning-hand.svg";
export { default as WaterIcon } from "./water.svg";
